---
apiVersion: v1
kind: Service
metadata:

  name: quorum-node-0
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node-0
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node-0-deployment
  # NodePort | ClusterIP | Loadbalancer
  type: NodePort
  ports:
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303

---

apiVersion: v1
kind: Service
metadata:

  name: quorum-node-0-rpc
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node-0-rpc
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node-0-deployment
  # NodePort | ClusterIP | Loadbalancer
  type: NodePort
  ports:
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545


