
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum-node-0-deployment

spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: quorum-node-0-deployment
  template:
    metadata:
      name:  quorum-node-0-deployment
      labels:
        app: qubernetes
        tier: backend
        name: quorum-node-0-deployment
    spec:
      initContainers:
        - name: quorum-genesis-init-container
          image: "{{ .Values.quorum_source.registry }}/{{ .Values.quorum_source.image }}:{{ .Values.quorum_source.version }}"
          command: [ "sh" ]
          args:
            - "-cx"
            - "if [ ! -f $QUORUM_DATA_DIR/genesis_created ]; then
              /usr/local/bin/geth --datadir $QUORUM_DATA_DIR init /etc/quorum/genesis/genesis-geth.json;
              date > $QUORUM_DATA_DIR/genesis_created;
           fi;
          "
          env:
            - name: QUORUM_DATA_DIR
              value: /etc/quorum/qdata/dd
            - name: QHOME
              value: /etc/quorum/qdata
          volumeMounts:
            - name: quorum-persistent-storage
              mountPath:  /etc/quorum/qdata
              subPath: quorum-node-0
            - name: genesis-config-persistent-storage
              mountPath: /etc/quorum/genesis/genesis-geth.json
              subPath: genesis-geth.json

      containers:
        - name: quorum
          image: "{{ .Values.quorum_source.registry }}/{{ .Values.quorum_source.image }}:{{ .Values.quorum_source.version }}"
          readinessProbe:
            exec:
              command:
                - ls
                - $(QHOME)/dd/geth.ipc
            initialDelaySeconds: 20
            periodSeconds: 3
          command: [ "sh" ]
          args:
            - "-cx"
            - "
           apk add jq;

           ln -s $QUORUM_HOME/permission-nodes/permissioned-nodes.json $QUORUM_DATA_DIR/permissioned-nodes.json;
           ln -s $QUORUM_HOME/permission-nodes/permissioned-nodes.json $QUORUM_DATA_DIR/static-nodes.json;

           cat /etc/quorum/genesis/genesis-geth.json;

           chmod 644 $QUORUM_DATA_DIR/keystore/key;

           touch $QUORUM_DATA_DIR/password.txt;
           NETWORK_ID=10
           RPC_APIS=admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum
           args=\" --gcmode archive --istanbul.blockperiod {{ .Values.blockhain.blockperiod }} --syncmode full --mine --miner.threads 1 \";
           RPC_APIS=\"$RPC_APIS,istanbul\";
           /usr/local/bin/geth \
           --datadir $QUORUM_DATA_DIR \
           $args \
           --permissioned \
           --nodiscover \
           --nat=none \
           --verbosity 3 \
           --networkid $NETWORK_ID \
           --emitcheckpoints \
           --port 30303 \
           --rpc \
           --rpcaddr 0.0.0.0 \
           --rpcport 8545 \
           --rpcapi $RPC_APIS \
           --rpccorsdomain=\"*\" \
           --rpcvhosts=quorum-node-0-rpc \
            2>&1 | tee -a /etc/quorum/qdata/logs/quorum.log;"
          ports:
            - containerPort: 8545
            - containerPort: 30303

          env:
            - name: PRIVATE_CONFIG
              value: "ignore"
            - name: QUORUM_DATA_DIR
              value: /etc/quorum/qdata/dd
            - name: QUORUM_HOME
              value: /etc/quorum/qdata
            - name: QHOME
              value: /etc/quorum/qdata
            - name: THIS_NODE_ID
              value: quorum-node-0
            - name: THIS_ENODE
              value: {{ .Values.quorum.enode }}
          volumeMounts:
            - name: quorum-persistent-storage
              mountPath: /etc/quorum/qdata
              subPath: quorum-node-0
            - name: quorum-persistent-storage-logs
              mountPath: /etc/quorum/qdata/logs
              subPath: quorum-node-0-logs
            - name: genesis-config-persistent-storage
              mountPath: /etc/quorum/genesis/genesis-geth.json
              subPath: genesis-geth.json
            - name: quorum-key-config-persistent-storage
              mountPath: /etc/quorum/qdata/dd/keystore/key
              subPath: key
            - name: quorum-nodekey
              mountPath: /etc/quorum/qdata/dd/geth/nodekey
              subPath: nodekey
            - name: quorum-enode
              mountPath: /etc/quorum/qdata/dd/geth/enode
              subPath: enode
            - name: quorum-permissioned-config
              mountPath: /etc/quorum/qdata/permission-nodes
            - name: geth-helpers
              mountPath: /geth-helpers
            - name: istanbul-validator-config
              mountPath: /etc/quorum/qdata/istanbul-validator-config.toml
            - name: node-management
              mountPath: /etc/quorum/qdata/node-management/ibft_propose.sh
              subPath: ibft_propose.sh
            - name: node-management
              mountPath: /etc/quorum/qdata/node-management/ibft_propose_all.sh
              subPath: ibft_propose_all.sh
      volumes:
        - name: quorum-permissioned-config
          configMap:
            name: quorum-permissioned-config
            items:
              - key: permissioned-nodes.json
                path: permissioned-nodes.json
        - name: genesis-config-persistent-storage
          configMap:
            name: genesis-config
            items:
              - key: genesis-geth.json
                path: genesis-geth.json
        - name: quorum-key-config-persistent-storage
          configMap:
            name: quorum-node-0-account-key-config
            items:
              - key: key
                path: key
        - name: quorum-nodekey
          configMap:
            name: quorum-node-0-nodekey-config
            items:
              - key: nodekey
                path: nodekey
        - name: quorum-enode
          configMap:
            name: quorum-node-0-enode-config
            items:
              - key: enode
                path: enode
        - name: geth-helpers
          configMap:
            name: geth-helpers
            items:
              - key: geth-attach.sh
                path: geth-attach.sh
              - key: geth-exec.sh
                path: geth-exec.sh
            defaultMode: 0777
        - name: istanbul-validator-config
          configMap:
            name: istanbul-validator-config.toml
        - name: node-management
          configMap:
            name: node-management
            items:
              - key: ibft_propose.sh
                path: ibft_propose.sh
              - key: ibft_propose_all.sh
                path: ibft_propose_all.sh
            defaultMode: 0777
        # PVC (configurable) https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
        - name: quorum-persistent-storage
          persistentVolumeClaim:
            claimName: quorum-node-0-pvc
        - name: quorum-persistent-storage-logs
          persistentVolumeClaim:
            claimName: quorum-node-0-logs-pvc
